openapi: 3.1.0
info:
  title: Email API
  version: 1.0.0
  description: Routes for sending transactional emails (e.g. donation thank you).

paths:
  /api/email/{transactionId}:
    post:
      summary: Send thank you email
      description: >
        Sends a thank you email to the participant associated with the given transaction ID.  
        Requires that the transaction exists and is linked to a participant with a valid email.
      tags:
        - Email
      parameters:
        - in: path
          name: transactionId
          required: true
          schema:
            type: string
          description: The ID of the transaction whose participant will receive the email.
      responses:
        "200":
          description: Email successfully sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  data:
                    type: object
                    description: Nodemailer response object
        "400":
          description: Missing or invalid transaction ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Missing transaction ID"
        "404":
          description: Transaction or participant not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Transaction does not exist"
        "500":
          description: Server error when sending email
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Thnx email Internal server error"
